### ISSUE TITLE
todo mind-dump

### ISSUE THREAD

**Issue by micgro42** [micgro42/cssColorNameFinder#1]
A rough todo mind-dump
**MVP**
- [ ] CI/CD
  - [x] GitHub Pages
  - [x] Fork-On-GitHub Banner
  - [x] Testing
  - [ ] sentry.io
- [x] Intro
  - [x] Label
  - [ ] ~~Text for no color selected (= Label as well)~~
- [ ] Styling
  - consider [skeleton css](http://getskeleton.com/)
- [x] refactoring to factory for use-case
- [ ] ensure it has _all_ valid colors! E.g. rebeccapurple is missing
  * [CSS Color Module Level 4 Editor’s Draft](https://drafts.csswg.org/css-color/#named-colors)

**Post-MVP**
- [ ] split-color view

**Version 2**
- [ ] offline PWA
- [ ] copy to clipboard on click / touch?
